//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.14 at 05:46:16 PM IST 
//


package bankloansoapwebservice.web.bank.soap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="bankloan" type="{http://soap.bank.web.bankloansoapwebservice}loan_scheme"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "bankloan"
})
@XmlRootElement(name = "createNewLoanRequest")
public class CreateNewLoanRequest {

    @XmlElement(required = true)
    protected LoanScheme bankloan;

    /**
     * Gets the value of the bankloan property.
     * 
     * @return
     *     possible object is
     *     {@link LoanScheme }
     *     
     */
    public LoanScheme getBankloan() {
        return bankloan;
    }

    /**
     * Sets the value of the bankloan property.
     * 
     * @param value
     *     allowed object is
     *     {@link LoanScheme }
     *     
     */
    public void setBankloan(LoanScheme value) {
        this.bankloan = value;
    }

}
